sudo: false
language: ruby
rvm:
  - 2.4.1

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - mboyaberry@gmail.com
      - cessmbuguar@gmail.com
    on_failure: change
    on_success: never
